# Site name
site_name: MS Fabric Labs
dev_addr: '0.0.0.0:8000'

# Navigation menu
nav:
  - Overview: index.md

  - "Microsoft Fabric":
    - "01 Lakehouse":
      - 01-lakehouse/index.md
      - Instructions: 01-lakehouse/instructions.md
    - "05 Dataflows (Gen2)": 
      - 05-dataflows-gen2/index.md
      - Instructions: 05-dataflows-gen2/instructions.md
    - "3b Medallion Architecture":
      - 03b-medallion-lakehouse/index.md
      - Instructions: 03b-medallion-lakehouse/instructions.md
    - "04 Ingest Pipeline":
      - 04-ingest-pipeline/index.md
      - Instructions: 04-ingest-pipeline/instructions.md
    - "06c Monitor Data Warehouse":
      - 06c-monitor-data-warehouse/index.md
      - Instructions: 06c-monitor-data-warehouse/instructions.md
    - "09 Real-time Eventstream":
      - 09-real-time-analytics-eventstream/index.md
      - Instructions: 09-real-time-analytics-eventstream/instructions.md
    - "18 Monitor Hub":
      - 18-monitor-hub/index.md
      - Instructions: 18-monitor-hub/instructions.md
    - "19 Secure Data Access":
      - 19-secure-data-access/index.md
      - Instructions: 19-secure-data-access/instructions.md
    - "21 Deployment Pipelines":
      - 21-deployment-pipelines/index.md
      - Instructions: 21-deployment-pipelines/instructions.md

# Theme
theme:
  name: material
  palette:
    primary: black
    accent: green
  features:
    - toc.integrate
    - content.code.copy
    - navigation.indexes   # makes section titles link to their index.md
  icon:
    logo: material/database
  static_templates:
    - 404.html

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: false
      toc_depth: 2

  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.tilde

plugins:
  - search
  - glightbox

