# Site name
site_name: MS Fabric Labs
dev_addr: '0.0.0.0:8000'

# Navigation menu
nav:
  - Overview: index.md

  - "Microsoft Fabric":

    - "01 Lakehouse":
      - 01-lakehouse/index.md
      - Summary: 01-lakehouse/summary.md

    - "3b Medallion Architecture":
      - 03b-medallion-lakehouse/index.md
      - Summary: 03b-medallion-lakehouse/summary.md

    - "04 Ingest Pipeline":
      - 04-ingest-pipeline/index.md
      - Summary: 04-ingest-pipeline/summary.md

    - "05 Dataflows (Gen2)": 
      - 05-dataflows-gen2/index.md
      - Summary: 05-dataflows-gen2/summary.md

    - "06 Analyse data in a data warehouse":
      - 06-data-warehouse/index.md
      - Summary: 06-data-warehouse/summary.md

    - "06c Monitor Data Warehouse":
      - 06c-monitor-data-warehouse/index.md
      - Summary: 06c-monitor-data-warehouse/summary.md

    - "09 Real-time Eventstream":
      - 09-real-time-analytics-eventstream/index.md
      - Summary: 09-real-time-analytics-eventstream/summary.md

    - "18 Monitor Hub":
      - 18-monitor-hub/index.md
      - Summary: 18-monitor-hub/summary.md

    - "19 Secure Data Access":
      - 19-secure-data-access/index.md
      - Summary: 19-secure-data-access/summary.md

    - "20 Work with SQL Database":
      - 20-work-with-database/index.md
      - Summary: 20-work-with-database/summary.md

    - "21 Deployment Pipelines":
      - 21-implement-cicd/index.md
      - Summary: 21-implement-cicd/summary.md

# Theme
theme:
  name: material
  palette:
    primary: black
    accent: green
  features:
    - toc.integrate
    - content.code.copy
    - navigation.indexes   # makes section titles link to their index.md
  icon:
    logo: material/database
  static_templates:
    - 404.html

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: false
      toc_depth: 2

  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.tilde

plugins:
  - search
  - glightbox
